### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by soryy708** [Sharonio/roboshaul#3]
README.md contains the text `the Robo-Shaul competition website and fill the small form there` which links to https://story.kan.org.il/robo_shaul/c/bb084921/?cardId=bb084921 but the link is broken.

It leads to https://story.kan.org.il/robo_shaul which responds with:

```xml
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>kan/robo_shaul</Key>
  <RequestId>1MKYPTD86DSJRK68</RequestId>
  <HostId>
    X5whERzNsgxOB+xNlnIU8kI4j+jjGimMwhZqlsBafXoMSFq+Tkz2ySWsaH3oJhuqlIOk0PMZo2o=
  </HostId>
</Error>
```

**Comment by Sharonio** [comment]
Hi thanks! we solved this
